# Generated by Django 4.2.7 on 2023-11-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('image_path', models.ImageField(upload_to='uploaded_images/')),
            ],
            options={
                'db_table': 'upload_image',
            },
        ),
    ]
