# Generated by Django 4.2.7 on 2023-11-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255)),
                ('info_url', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('image_path', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('image_path', models.ImageField(upload_to='uploaded_images/')),
            ],
            options={
                'db_table': 'upload_image',
            },
        ),
    ]
