# Generated by Django 4.2.7 on 2023-11-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('isGuideChecked', models.BooleanField(default=False)),
                ('nickname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
